### ISSUE TITLE
Enumerate timeseries object is out of bounds for some files on LiPDverse

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#156]
**Describe the bug**
ts = D.to_LipdSeries()
extracting paleoData...
extracting: HeshangCave.Wang.2018
Created time series: 4 entries
0 :  HeshangCave.Wang.2018 :  Speleothem :  sampleID
1 :  HeshangCave.Wang.2018 :  Speleothem :  sample
2 :  HeshangCave.Wang.2018 :  Speleothem :  age
3 :  HeshangCave.Wang.2018 :  Speleothem :  RAN15
Traceback (most recent call last):

  File "<ipython-input-4-9643d06b3956>", line 1, in <module>
    ts = D.to_LipdSeries()

  File "/Users/deborahkhider/opt/anaconda3/envs/pyleoclim/lib/python3.8/site-packages/pyleoclim/core/ui.py", line 6071, in to_LipdSeries
    ts = LipdSeries(ts_list)

  File "/Users/deborahkhider/opt/anaconda3/envs/pyleoclim/lib/python3.8/site-packages/pyleoclim/core/ui.py", line 6270, in __init__
    self.lipd_ts=lipdutils.getTs(tso)

  File "/Users/deborahkhider/opt/anaconda3/envs/pyleoclim/lib/python3.8/site-packages/pyleoclim/utils/lipdutils.py", line 474, in getTs
    enumerateTs(timeseries_list)

  File "/Users/deborahkhider/opt/anaconda3/envs/pyleoclim/lib/python3.8/site-packages/pyleoclim/utils/lipdutils.py", line 451, in enumerateTs
    print(idx,': ',dataSetName[idx], ': ',at[idx],': ', val)

IndexError: list index out of range

**To Reproduce**
D = pyleo.Lipd('/Users/deborahkhider/Downloads/HeshangCave.Wang.2018.lpd')
ts = D.to_LipdSeries()

**Comment by khider** [comment]
Problem: the flexibility of the name field in enumerateTS to allow for chron and paleo created double entries when the field `paleoData_variableNameOriginal` was present. 

Fixed in commit#[d1d084e](https://github.com/LinkedEarth/Pyleoclim_util/commit/d1d084e3ffd50500d8dc3319d5d4334e4db5c0e0)
