### ISSUE TITLE
Error on plot_envelope

### ISSUE THREAD

**Issue by khider** [LinkedEarth/Pyleoclim_util#190]
The problem is when NaNs are present in the ensemble members. 

To reproduce. Use data from: https://github.com/LinkedEarth/PyleoclimPaper/blob/main/MarineSediment%20TimeSeries%20Analysis/MD982181.Khider.2014.lpd

In Python:
```
import pyleoclim as pyleo
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
pyleo.set_style('web')


D = pyleo.Lipd('MD982181.Khider.2014.lpd')

sst_ens = sst.chronEnsembleToPaleo(D,number=100, chronNumber=0,modelNumber=0, tableNumber=0)
sst_ens.common_time().plot_envelope()
```

Error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/xj/p7h9764x7cx0by8547l04rrr0000gn/T/ipykernel_1828/1052190229.py in <module>
----> 1 sst_ens.common_time().plot_envelope()

~/opt/anaconda3/envs/paleodev/lib/python3.9/site-packages/pyleoclim/core/ui.py in plot_envelope(self, figsize, qs, xlabel, ylabel, title, xlim, ylim, savefig_settings, ax, plot_legend, curve_clr, curve_lw, shade_clr, shade_alpha, inner_shade_label, outer_shade_label, lgd_kwargs, mute)
   5509         )
   5510         # plot inner envelope on top
-> 5511         ax.fill_between(
   5512             time, ts_qs.series_list[1].value, ts_qs.series_list[3].value,
   5513             color=shade_clr, alpha=2*shade_alpha, edgecolor=shade_clr, label=inner_shade_label,

~/opt/anaconda3/envs/paleodev/lib/python3.9/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1359     def inner(ax, *args, data=None, **kwargs):
   1360         if data is None:
-> 1361             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1362 
   1363         bound = new_sig.bind(ax, *args, **kwargs)

~/opt/anaconda3/envs/paleodev/lib/python3.9/site-packages/matplotlib/axes/_axes.py in fill_between(self, x, y1, y2, where, interpolate, step, **kwargs)
   5384     def fill_between(self, x, y1, y2=0, where=None, interpolate=False,
   5385                      step=None, **kwargs):
-> 5386         return self._fill_between_x_or_y(
   5387             "x", x, y1, y2,
   5388             where=where, interpolate=interpolate, step=step, **kwargs)

~/opt/anaconda3/envs/paleodev/lib/python3.9/site-packages/matplotlib/axes/_axes.py in _fill_between_x_or_y(self, ind_dir, ind, dep1, dep2, where, interpolate, step, **kwargs)
   5306                 raise ValueError(f"where size ({where.size}) does not match "
   5307                                  f"{ind_dir} size ({ind.size})")
-> 5308         where = where & ~functools.reduce(
   5309             np.logical_or, map(np.ma.getmask, [ind, dep1, dep2]))
   5310 

ValueError: operands could not be broadcast together with shapes (8,) (5,) 
```

**Comment by khider** [comment]
In this case, `common_time` drops the majority of the timeseries.

**Comment by CommonClimate** [comment]
this is the error I get:
`File "/var/folders/bf/_x19bm694857h_hrw44j0p7w0000gn/T/ipykernel_75465/1050251495.py", line 11, in <module>
    sst_ens = sst.chronEnsembleToPaleo(D,number=100, chronNumber=0,modelNumber=0, tableNumber=0)

NameError: name 'sst' is not defined`

**Comment by CommonClimate** [comment]
You must have left out at least one line. sst is not defined:

```
Traceback (most recent call last):

  File "/var/folders/bf/_x19bm694857h_hrw44j0p7w0000gn/T/ipykernel_75465/1050251495.py", line 11, in <module>
    sst_ens = sst.chronEnsembleToPaleo(D,number=100, chronNumber=0,modelNumber=0, tableNumber=0)

NameError: name 'sst' is not defined
```

**Comment by khider** [comment]
```
sst = D.to_LipdSeries(number=4)
d18Osw = D.to_LipdSeries(number=5)
mund = D.to_LipdSeries(number=8)
```

**Comment by khider** [comment]
Better error handling is needed here.
