### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\LMRt_project\\PAGES2k_CCSM4_GISTEMP\\data\\prior\\SST\\b.e11.BLMTRC5CN.f19_g16.001.pop.h.SST.085001-200512.96144.d3'

### ISSUE THREAD

**Issue by rihpeach** [LinkedEarth/Pyleoclim_util#613]
Traceback (most recent call last):
  File "E:\LMRt_project\fuxian\li13b6_ch296_d20v3_dropCM1_year_da.py", line 93, in <module>
    job.load_prior(verbose=True)
  File "E:\Anaconda\envs\lmrt\lib\site-packages\LMRt\reconjob.py", line 462, in load_prior
    ds.load_nc(self.configs['prior_path'], varname_dict=self.configs['prior_varname'], anom_period=anom_period, inplace=True)
  File "E:\Anaconda\envs\lmrt\lib\site-packages\LMRt\gridded.py", line 227, in load_nc
    with xr.open_dataset(path, engine='netcdf4') as ds:
  File "E:\Anaconda\envs\lmrt\lib\site-packages\xarray\backends\api.py", line 588, in open_dataset
    backend_ds = backend.open_dataset(
  File "E:\Anaconda\envs\lmrt\lib\site-packages\xarray\backends\netCDF4_.py", line 645, in open_dataset
    store = NetCDF4DataStore.open(
  File "E:\Anaconda\envs\lmrt\lib\site-packages\xarray\backends\netCDF4_.py", line 408, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "E:\Anaconda\envs\lmrt\lib\site-packages\xarray\backends\netCDF4_.py", line 355, in __init__
    self.format = self.ds.data_model
  File "E:\Anaconda\envs\lmrt\lib\site-packages\xarray\backends\netCDF4_.py", line 417, in ds
    return self._acquire()
  File "E:\Anaconda\envs\lmrt\lib\site-packages\xarray\backends\netCDF4_.py", line 411, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "E:\Anaconda\envs\lmrt\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "E:\Anaconda\envs\lmrt\lib\site-packages\xarray\backends\file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "E:\Anaconda\envs\lmrt\lib\site-packages\xarray\backends\file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "src\\netCDF4\\_netCDF4.pyx", line 2470, in netCDF4._netCDF4.Dataset.__init__
  File "src\\netCDF4\\_netCDF4.pyx", line 2107, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\LMRt_project\\PAGES2k_CCSM4_GISTEMP\\data\\prior\\SST\\b.e11.BLMTRC5CN.f19_g16.001.pop.h.SST.085001-200512.96144.d3'
![1727170162856](https://github.com/user-attachments/assets/b6078213-7479-4c3c-88e6-fb8a084b56d4)
![1727170195651](https://github.com/user-attachments/assets/1164c57d-f567-47a4-941a-04530b4812ea)

**Comment by rihpeach** [comment]
Hello, I encountered an issue loading files during data assimilation. My path, naming, and permissions are all fine, and I have also set up with xr.open_dataset (path, engine='netcdf4') as ds:， But it still reports an error, showing that the file cannot be found.

**Comment by CommonClimate** [comment]
Hello @rihpeach , sorry you are encountering this issue, but this is not the place to report it: it seems an issue with `xarray`, so I would ask for advice on the [pangeo forum](https://discourse.pangeo.io). However, the problem seems more elementary: it's just that the file cannot be found at the specified path.

I also note that you appear to be using the LMRt package, which has been discontinued. Please use [cfr](https://fzhu2e.github.io/cfr) instead. It should simplify the downloading of necessary files, so it may solve the issue above.

**Comment by CommonClimate** [comment]
I am closing this as it is definitely not a Pyleoclim issue
